import Providers from "./Providers";
import Header from "./components/Header";
import NavBar from "./components/NavBar";
import SearchBar from "./components/SearchBar";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang='en'>
      <body suppressHydrationWarning={true}>
        <Providers>
          <Header />
          <NavBar />
          <SearchBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
